version: '3.4'

services:
  db:
    container_name: desafio-dev-db
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    container_name: desafio-dev-api
    build: .
    image: desafio-dev-api
    restart: unless-stopped
    working_dir: /usr/api
    volumes:
      - .:/usr/api
      - /usr/api/node_modules
    ports:
      - '3000:3000'    
    command: npm run server
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
